//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApiPermission()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public string PermissionName { get; set; }
        public Nullable<bool> CanRead { get; set; }
        public Nullable<bool> CanWrite { get; set; }
        public Nullable<bool> CanAlterPermissions { get; set; }
        public int ApiPermissionsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
