//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string ClientName { get; set; }
        public bool IsDeleted { get; set; }
        public string ClientKey { get; set; }
        public int ClientId { get; set; }
        public int PermissionsId { get; set; }
    
        public virtual ApiPermission ApiPermission { get; set; }
    }
}
