//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioDBEntities : DbContext
    {
        public PortfolioDBEntities(string connStr)
            : base(connStr)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApiPermission> ApiPermissions { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<GithubUser> GithubUsers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole_Map> UserRole_Map { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
